#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WIDTH 800
#define HEIGHT 600
#define BULLET_MOVE 50
#define PLAYER_MOVE 10
#define ENEMY_MOVE 50
#define PLAYER 100
#define BULLET_HI 50
#define BULLET_W 50
#define ENEMIES_CREATING 2000
#define BONUS_MOVE 50
#define BONUS_CREATING 10000
#endif // CONSTANTS_H
